import { useState } from 'react'
import { Routes, Route, useNavigate } from 'react-router-dom'
import { Plus, Download, Filter, Eye, Edit2, Copy, RotateCcw, Trash2, Check, X } from 'lucide-react'
import { Button, Card, Modal, Input, Select, Badge, SearchInput, Tabs } from '../../components/ui'
import type { JournalEntry, JournalEntryLine, ChartOfAccount } from '../../types'

// Mock accounts for dropdowns
const mockAccounts: ChartOfAccount[] = [
  { id: 3, accountCode: '1101', accountName: 'Cash on Hand', parentId: 2, accountCategoryId: 1, accountLevel: 3, isHeader: false, isPosting: true, normalBalance: 'DEBIT', isActive: true, isSystem: true, createdAt: '2026-01-01' },
  { id: 4, accountCode: '1102', accountName: 'Bank Accounts', parentId: 2, accountCategoryId: 1, accountLevel: 3, isHeader: false, isPosting: true, normalBalance: 'DEBIT', isActive: true, isSystem: true, createdAt: '2026-01-01' },
  { id: 5, accountCode: '1103', accountName: 'Accounts Receivable', parentId: 2, accountCategoryId: 1, accountLevel: 3, isHeader: false, isPosting: true, normalBalance: 'DEBIT', isActive: true, isSystem: true, createdAt: '2026-01-01' },
  { id: 9, accountCode: '2101', accountName: 'Accounts Payable', parentId: 8, accountCategoryId: 2, accountLevel: 3, isHeader: false, isPosting: true, normalBalance: 'CREDIT', isActive: true, isSystem: true, createdAt: '2026-01-01' },
]

// Mock journal entries
const mockEntries: JournalEntry[] = [
  {
    id: 1, entryNumber: 'JE-2026-0042', entryType: 'ACTUAL', entryDate: '2026-02-04', fiscalPeriodId: 2,
    referenceNumber: 'INV-001', description: 'Customer payment received', totalDebit: 50000, totalCredit: 50000,
    status: 'POSTED', isAutoGenerated: false, createdAt: '2026-02-04',
    lines: [
      { lineNumber: 1, accountId: 3, creditOrDebitId: 1, amount: 50000, description: 'Cash received' },
      { lineNumber: 2, accountId: 5, creditOrDebitId: 2, amount: 50000, description: 'AR reduced' }
    ]
  },
  {
    id: 2, entryNumber: 'JE-2026-0041', entryType: 'ACTUAL', entryDate: '2026-02-03', fiscalPeriodId: 2,
    referenceNumber: 'PO-042', description: 'Payment to supplier', totalDebit: 25000, totalCredit: 25000,
    status: 'POSTED', isAutoGenerated: false, createdAt: '2026-02-03',
    lines: [
      { lineNumber: 1, accountId: 9, creditOrDebitId: 1, amount: 25000, description: 'AP reduced' },
      { lineNumber: 2, accountId: 4, creditOrDebitId: 2, amount: 25000, description: 'Bank payment' }
    ]
  },
  {
    id: 3, entryNumber: 'JE-2026-0040', entryType: 'BUDGET', entryDate: '2026-02-01', fiscalPeriodId: 2,
    description: 'February budget allocation', totalDebit: 100000, totalCredit: 100000,
    status: 'POSTED', isAutoGenerated: false, createdAt: '2026-02-01',
    lines: []
  },
  {
    id: 4, entryNumber: 'JE-2026-0039', entryType: 'ACTUAL', entryDate: '2026-02-01', fiscalPeriodId: 2,
    description: 'Office supplies purchase', totalDebit: 15000, totalCredit: 15000,
    status: 'PENDING', isAutoGenerated: false, createdAt: '2026-02-01',
    lines: []
  },
  {
    id: 5, entryNumber: 'JE-2026-0038', entryType: 'ACTUAL', entryDate: '2026-01-31', fiscalPeriodId: 1,
    description: 'Month-end adjustments', totalDebit: 75000, totalCredit: 75000,
    status: 'DRAFT', isAutoGenerated: false, createdAt: '2026-01-31',
    lines: []
  },
]

const statusColors: Record<string, 'default' | 'warning' | 'success' | 'danger'> = {
  DRAFT: 'default',
  PENDING: 'warning',
  POSTED: 'success',
  REVERSED: 'danger'
}

// Journal Entry Form Component
function JournalEntryForm({ entry, onClose }: { entry?: JournalEntry | null; onClose: () => void }) {
  const [lines, setLines] = useState<JournalEntryLine[]>(entry?.lines || [
    { lineNumber: 1, accountId: 0, creditOrDebitId: 1, amount: 0, description: '' },
    { lineNumber: 2, accountId: 0, creditOrDebitId: 2, amount: 0, description: '' }
  ])

  const addLine = () => {
    setLines([...lines, { lineNumber: lines.length + 1, accountId: 0, creditOrDebitId: 1, amount: 0, description: '' }])
  }

  const removeLine = (index: number) => {
    if (lines.length > 2) {
      setLines(lines.filter((_, i) => i !== index))
    }
  }

  const totalDebit = lines.filter(l => l.creditOrDebitId === 1).reduce((sum, l) => sum + l.amount, 0)
  const totalCredit = lines.filter(l => l.creditOrDebitId === 2).reduce((sum, l) => sum + l.amount, 0)
  const isBalanced = totalDebit === totalCredit && totalDebit > 0

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-4 gap-4">
        <Input label="Entry Number" defaultValue={entry?.entryNumber || 'Auto-generated'} disabled />
        <Input label="Entry Date" type="date" defaultValue={entry?.entryDate || new Date().toISOString().split('T')[0]} required />
        <Select
          label="Entry Type"
          options={[
            { value: 'ACTUAL', label: 'Actual Entry' },
            { value: 'BUDGET', label: 'Budget Entry' }
          ]}
          defaultValue={entry?.entryType || 'ACTUAL'}
          required
        />
        <Select
          label="Fiscal Period"
          options={[
            { value: 1, label: 'January 2026' },
            { value: 2, label: 'February 2026' },
            { value: 3, label: 'March 2026' }
          ]}
          defaultValue={entry?.fiscalPeriodId || 2}
          required
        />
      </div>

      <div className="grid grid-cols-2 gap-4">
        <Input label="Reference Number" placeholder="e.g., INV-001" defaultValue={entry?.referenceNumber} />
        <Input label="Description" placeholder="Brief description of the entry" defaultValue={entry?.description} required />
      </div>

      <div>
        <div className="flex items-center justify-between mb-3">
          <h4 className="font-medium text-secondary-900">Line Items</h4>
          <Button variant="outline" size="sm" leftIcon={<Plus className="w-4 h-4" />} onClick={addLine}>
            Add Line
          </Button>
        </div>

        <div className="border border-secondary-200 rounded-lg overflow-hidden">
          <table className="w-full">
            <thead className="bg-secondary-50">
              <tr>
                <th className="px-3 py-2 text-left text-xs font-semibold text-secondary-600 uppercase w-12">#</th>
                <th className="px-3 py-2 text-left text-xs font-semibold text-secondary-600 uppercase">Account</th>
                <th className="px-3 py-2 text-left text-xs font-semibold text-secondary-600 uppercase w-28">Type</th>
                <th className="px-3 py-2 text-right text-xs font-semibold text-secondary-600 uppercase w-36">Amount</th>
                <th className="px-3 py-2 text-left text-xs font-semibold text-secondary-600 uppercase">Description</th>
                <th className="px-3 py-2 w-12"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-secondary-100">
              {lines.map((line, index) => (
                <tr key={index} className="bg-white">
                  <td className="px-3 py-2 text-sm text-secondary-500">{index + 1}</td>
                  <td className="px-3 py-2">
                    <select className="w-full text-sm border border-secondary-300 rounded px-2 py-1.5" defaultValue={line.accountId}>
                      <option value="">Select account...</option>
                      {mockAccounts.map(acc => (
                        <option key={acc.id} value={acc.id}>{acc.accountCode} - {acc.accountName}</option>
                      ))}
                    </select>
                  </td>
                  <td className="px-3 py-2">
                    <select className="w-full text-sm border border-secondary-300 rounded px-2 py-1.5" defaultValue={line.creditOrDebitId}>
                      <option value={1}>Debit</option>
                      <option value={2}>Credit</option>
                    </select>
                  </td>
                  <td className="px-3 py-2">
                    <input
                      type="number"
                      className="w-full text-sm text-right border border-secondary-300 rounded px-2 py-1.5"
                      placeholder="0.00"
                      defaultValue={line.amount || ''}
                    />
                  </td>
                  <td className="px-3 py-2">
                    <input
                      type="text"
                      className="w-full text-sm border border-secondary-300 rounded px-2 py-1.5"
                      placeholder="Line description"
                      defaultValue={line.description}
                    />
                  </td>
                  <td className="px-3 py-2">
                    {lines.length > 2 && (
                      <button onClick={() => removeLine(index)} className="text-red-500 hover:text-red-700">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot className="bg-secondary-50 border-t-2">
              <tr>
                <td colSpan={3} className="px-3 py-2 text-right font-semibold text-secondary-700">Totals:</td>
                <td className="px-3 py-2 text-right">
                  <div className="text-sm">
                    <span className="text-secondary-500">DR:</span> <span className="font-mono font-semibold">{totalDebit.toLocaleString()}</span>
                  </div>
                  <div className="text-sm">
                    <span className="text-secondary-500">CR:</span> <span className="font-mono font-semibold">{totalCredit.toLocaleString()}</span>
                  </div>
                </td>
                <td className="px-3 py-2">
                  {isBalanced ? (
                    <Badge variant="success">Balanced</Badge>
                  ) : (
                    <Badge variant="danger">Unbalanced</Badge>
                  )}
                </td>
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>

      <div className="flex justify-end gap-3 pt-4 border-t">
        <Button variant="outline" onClick={onClose}>Cancel</Button>
        <Button variant="secondary">Save as Draft</Button>
        <Button disabled={!isBalanced}>Post Entry</Button>
      </div>
    </div>
  )
}

// Journal Entry List
function JournalEntryList() {
  const navigate = useNavigate()
  const [search, setSearch] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [selectedEntry, setSelectedEntry] = useState<JournalEntry | null>(null)
  const [statusFilter, setStatusFilter] = useState<string>('all')
  const [typeFilter, setTypeFilter] = useState<string>('all')

  const filteredEntries = mockEntries.filter(e => {
    const matchesSearch = e.entryNumber.toLowerCase().includes(search.toLowerCase()) ||
      e.description.toLowerCase().includes(search.toLowerCase())
    const matchesStatus = statusFilter === 'all' || e.status === statusFilter
    const matchesType = typeFilter === 'all' || e.entryType === typeFilter
    return matchesSearch && matchesStatus && matchesType
  })

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-secondary-900">Journal Entries</h1>
          <p className="text-secondary-500 mt-1">Create and manage journal entries</p>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" leftIcon={<Download className="w-4 h-4" />}>Export</Button>
          <Button leftIcon={<Plus className="w-4 h-4" />} onClick={() => { setSelectedEntry(null); setShowModal(true) }}>
            New Entry
          </Button>
        </div>
      </div>

      <Card>
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <SearchInput value={search} onChange={setSearch} placeholder="Search entries..." className="w-72" />
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="border border-secondary-300 rounded-lg px-3 py-2 text-sm"
            >
              <option value="all">All Status</option>
              <option value="DRAFT">Draft</option>
              <option value="PENDING">Pending</option>
              <option value="POSTED">Posted</option>
              <option value="REVERSED">Reversed</option>
            </select>
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              className="border border-secondary-300 rounded-lg px-3 py-2 text-sm"
            >
              <option value="all">All Types</option>
              <option value="ACTUAL">Actual</option>
              <option value="BUDGET">Budget</option>
            </select>
          </div>
          <div className="text-sm text-secondary-500">{filteredEntries.length} entries</div>
        </div>

        <div className="border border-secondary-200 rounded-lg overflow-hidden">
          <table className="w-full">
            <thead className="bg-secondary-50 border-b">
              <tr>
                <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Entry #</th>
                <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Date</th>
                <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Type</th>
                <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Description</th>
                <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Debit</th>
                <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Credit</th>
                <th className="px-4 py-3 text-center text-xs font-semibold text-secondary-600 uppercase">Status</th>
                <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-secondary-100">
              {filteredEntries.map(entry => (
                <tr key={entry.id} className="hover:bg-secondary-50 cursor-pointer" onClick={() => navigate(`/journal-entries/${entry.id}`)}>
                  <td className="px-4 py-3 font-mono text-sm font-medium text-primary-600">{entry.entryNumber}</td>
                  <td className="px-4 py-3 text-sm">{entry.entryDate}</td>
                  <td className="px-4 py-3">
                    <Badge variant={entry.entryType === 'ACTUAL' ? 'info' : 'purple'} size="sm">{entry.entryType}</Badge>
                  </td>
                  <td className="px-4 py-3 text-sm max-w-xs truncate">{entry.description}</td>
                  <td className="px-4 py-3 text-sm text-right font-mono">{entry.totalDebit.toLocaleString()}</td>
                  <td className="px-4 py-3 text-sm text-right font-mono">{entry.totalCredit.toLocaleString()}</td>
                  <td className="px-4 py-3 text-center">
                    <Badge variant={statusColors[entry.status]}>{entry.status}</Badge>
                  </td>
                  <td className="px-4 py-3 text-right" onClick={(e) => e.stopPropagation()}>
                    <div className="flex justify-end gap-1">
                      <button className="p-1 hover:bg-secondary-200 rounded" title="View">
                        <Eye className="w-4 h-4 text-secondary-500" />
                      </button>
                      {entry.status === 'DRAFT' && (
                        <button className="p-1 hover:bg-secondary-200 rounded" title="Edit" onClick={() => { setSelectedEntry(entry); setShowModal(true) }}>
                          <Edit2 className="w-4 h-4 text-secondary-500" />
                        </button>
                      )}
                      <button className="p-1 hover:bg-secondary-200 rounded" title="Duplicate">
                        <Copy className="w-4 h-4 text-secondary-500" />
                      </button>
                      {entry.status === 'POSTED' && (
                        <button className="p-1 hover:bg-red-100 rounded" title="Reverse">
                          <RotateCcw className="w-4 h-4 text-red-500" />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <Modal isOpen={showModal} onClose={() => setShowModal(false)} title={selectedEntry ? 'Edit Journal Entry' : 'New Journal Entry'} size="full">
        <JournalEntryForm entry={selectedEntry} onClose={() => setShowModal(false)} />
      </Modal>
    </div>
  )
}

// Journal Entry Detail
function JournalEntryDetail() {
  const navigate = useNavigate()
  const entry = mockEntries[0]

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <button onClick={() => navigate('/journal-entries')} className="text-primary-600 hover:text-primary-700 text-sm mb-2">
            ← Back to Journal Entries
          </button>
          <h1 className="text-2xl font-bold text-secondary-900">{entry.entryNumber}</h1>
          <p className="text-secondary-500">{entry.description}</p>
        </div>
        <div className="flex items-center gap-3">
          {entry.status === 'PENDING' && (
            <>
              <Button variant="danger" leftIcon={<X className="w-4 h-4" />}>Reject</Button>
              <Button variant="success" leftIcon={<Check className="w-4 h-4" />}>Approve & Post</Button>
            </>
          )}
          {entry.status === 'POSTED' && (
            <Button variant="outline" leftIcon={<RotateCcw className="w-4 h-4" />}>Reverse Entry</Button>
          )}
          <Button variant="outline" leftIcon={<Copy className="w-4 h-4" />}>Duplicate</Button>
        </div>
      </div>

      <div className="grid grid-cols-4 gap-6">
        <Card>
          <div className="text-center">
            <p className="text-sm text-secondary-500">Entry Date</p>
            <p className="text-lg font-semibold">{entry.entryDate}</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-sm text-secondary-500">Entry Type</p>
            <Badge variant={entry.entryType === 'ACTUAL' ? 'info' : 'purple'}>{entry.entryType}</Badge>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-sm text-secondary-500">Total Amount</p>
            <p className="text-lg font-semibold font-mono">LKR {entry.totalDebit.toLocaleString()}</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-sm text-secondary-500">Status</p>
            <Badge variant={statusColors[entry.status]}>{entry.status}</Badge>
          </div>
        </Card>
      </div>

      <Card title="Line Items" noPadding>
        <table className="w-full">
          <thead className="bg-secondary-50 border-b">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase w-12">#</th>
              <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Account</th>
              <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Description</th>
              <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Debit</th>
              <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Credit</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-secondary-100">
            <tr>
              <td className="px-4 py-3 text-sm">1</td>
              <td className="px-4 py-3"><span className="font-mono text-sm">1101</span> - Cash on Hand</td>
              <td className="px-4 py-3 text-sm text-secondary-600">Cash received</td>
              <td className="px-4 py-3 text-right font-mono">50,000.00</td>
              <td className="px-4 py-3 text-right font-mono text-secondary-400">-</td>
            </tr>
            <tr>
              <td className="px-4 py-3 text-sm">2</td>
              <td className="px-4 py-3"><span className="font-mono text-sm">1103</span> - Accounts Receivable</td>
              <td className="px-4 py-3 text-sm text-secondary-600">AR reduced</td>
              <td className="px-4 py-3 text-right font-mono text-secondary-400">-</td>
              <td className="px-4 py-3 text-right font-mono">50,000.00</td>
            </tr>
          </tbody>
          <tfoot className="bg-secondary-50 border-t-2">
            <tr>
              <td colSpan={3} className="px-4 py-3 text-right font-semibold">Totals:</td>
              <td className="px-4 py-3 text-right font-mono font-semibold">50,000.00</td>
              <td className="px-4 py-3 text-right font-mono font-semibold">50,000.00</td>
            </tr>
          </tfoot>
        </table>
      </Card>

      <Card title="Entry History">
        <div className="space-y-3">
          <div className="flex items-center gap-3 text-sm">
            <div className="w-2 h-2 bg-green-500 rounded-full"></div>
            <span className="text-secondary-500">Feb 4, 2026 10:30 AM</span>
            <span>Entry posted by <strong>Admin User</strong></span>
          </div>
          <div className="flex items-center gap-3 text-sm">
            <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
            <span className="text-secondary-500">Feb 4, 2026 10:15 AM</span>
            <span>Entry created by <strong>Admin User</strong></span>
          </div>
        </div>
      </Card>
    </div>
  )
}

// Pending Approvals
function PendingApprovals() {
  const pendingEntries = mockEntries.filter(e => e.status === 'PENDING')

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-secondary-900">Pending Approvals</h1>
        <p className="text-secondary-500 mt-1">Review and approve pending journal entries</p>
      </div>

      <Card noPadding>
        <table className="w-full">
          <thead className="bg-secondary-50 border-b">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Entry #</th>
              <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Date</th>
              <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Description</th>
              <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Amount</th>
              <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Created By</th>
              <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            {pendingEntries.length === 0 ? (
              <tr><td colSpan={6} className="px-4 py-8 text-center text-secondary-500">No pending approvals</td></tr>
            ) : (
              pendingEntries.map(entry => (
                <tr key={entry.id} className="hover:bg-secondary-50">
                  <td className="px-4 py-3 font-mono text-sm font-medium">{entry.entryNumber}</td>
                  <td className="px-4 py-3 text-sm">{entry.entryDate}</td>
                  <td className="px-4 py-3 text-sm">{entry.description}</td>
                  <td className="px-4 py-3 text-right font-mono">LKR {entry.totalDebit.toLocaleString()}</td>
                  <td className="px-4 py-3 text-sm">Admin User</td>
                  <td className="px-4 py-3 text-right">
                    <div className="flex justify-end gap-2">
                      <Button variant="danger" size="sm" leftIcon={<X className="w-3 h-3" />}>Reject</Button>
                      <Button variant="success" size="sm" leftIcon={<Check className="w-3 h-3" />}>Approve</Button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </Card>
    </div>
  )
}

// Budget vs Actual
function BudgetVsActual() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-secondary-900">Budget vs Actual</h1>
          <p className="text-secondary-500 mt-1">Compare budgeted amounts with actual transactions</p>
        </div>
        <div className="flex items-center gap-3">
          <Select
            options={[
              { value: 2, label: 'February 2026' },
              { value: 1, label: 'January 2026' }
            ]}
            defaultValue={2}
          />
          <Button variant="outline" leftIcon={<Download className="w-4 h-4" />}>Export</Button>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-6">
        <Card>
          <div className="text-center">
            <p className="text-sm text-secondary-500">Total Budget</p>
            <p className="text-2xl font-bold text-secondary-900">LKR 500,000</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-sm text-secondary-500">Total Actual</p>
            <p className="text-2xl font-bold text-secondary-900">LKR 340,000</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-sm text-secondary-500">Variance</p>
            <p className="text-2xl font-bold text-green-600">LKR 160,000</p>
            <p className="text-sm text-green-600">32% under budget</p>
          </div>
        </Card>
      </div>

      <Card title="By Account Category" noPadding>
        <table className="w-full">
          <thead className="bg-secondary-50 border-b">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-semibold text-secondary-600 uppercase">Category</th>
              <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Budget</th>
              <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Actual</th>
              <th className="px-4 py-3 text-right text-xs font-semibold text-secondary-600 uppercase">Variance</th>
              <th className="px-4 py-3 text-center text-xs font-semibold text-secondary-600 uppercase">% Used</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            <tr className="hover:bg-secondary-50">
              <td className="px-4 py-3 font-medium">Operating Expenses</td>
              <td className="px-4 py-3 text-right font-mono">200,000</td>
              <td className="px-4 py-3 text-right font-mono">150,000</td>
              <td className="px-4 py-3 text-right font-mono text-green-600">50,000</td>
              <td className="px-4 py-3 text-center">
                <div className="w-full bg-secondary-200 rounded-full h-2">
                  <div className="bg-green-500 h-2 rounded-full" style={{ width: '75%' }}></div>
                </div>
                <span className="text-xs text-secondary-500">75%</span>
              </td>
            </tr>
            <tr className="hover:bg-secondary-50">
              <td className="px-4 py-3 font-medium">Salaries</td>
              <td className="px-4 py-3 text-right font-mono">250,000</td>
              <td className="px-4 py-3 text-right font-mono">160,000</td>
              <td className="px-4 py-3 text-right font-mono text-green-600">90,000</td>
              <td className="px-4 py-3 text-center">
                <div className="w-full bg-secondary-200 rounded-full h-2">
                  <div className="bg-green-500 h-2 rounded-full" style={{ width: '64%' }}></div>
                </div>
                <span className="text-xs text-secondary-500">64%</span>
              </td>
            </tr>
            <tr className="hover:bg-secondary-50">
              <td className="px-4 py-3 font-medium">Marketing</td>
              <td className="px-4 py-3 text-right font-mono">50,000</td>
              <td className="px-4 py-3 text-right font-mono">30,000</td>
              <td className="px-4 py-3 text-right font-mono text-green-600">20,000</td>
              <td className="px-4 py-3 text-center">
                <div className="w-full bg-secondary-200 rounded-full h-2">
                  <div className="bg-green-500 h-2 rounded-full" style={{ width: '60%' }}></div>
                </div>
                <span className="text-xs text-secondary-500">60%</span>
              </td>
            </tr>
          </tbody>
        </table>
      </Card>
    </div>
  )
}

// Main Router
export default function JournalEntries() {
  return (
    <Routes>
      <Route index element={<JournalEntryList />} />
      <Route path="approvals" element={<PendingApprovals />} />
      <Route path="budget" element={<BudgetVsActual />} />
      <Route path=":id" element={<JournalEntryDetail />} />
    </Routes>
  )
}
