// TypeScript interfaces matching the database schema

export interface AccountCategory {
  id: number;
  categoryCode: string;
  categoryName: string;
  normalBalance: 'DEBIT' | 'CREDIT';
  displayOrder: number;
  isActive: boolean;
}

export interface ChartOfAccount {
  id: number;
  accountCode: string;
  accountName: string;
  parentId: number | null;
  accountCategoryId: number;
  accountCategory?: AccountCategory;
  accountLevel: number;
  isHeader: boolean;
  isPosting: boolean;
  normalBalance: 'DEBIT' | 'CREDIT';
  description?: string;
  isActive: boolean;
  isSystem: boolean;
  children?: ChartOfAccount[];
  createdAt: string;
}

export interface FiscalYear {
  id: number;
  yearCode: string;
  yearName: string;
  startDate: string;
  endDate: string;
  isClosed: boolean;
  closedBy?: number;
  closedAt?: string;
  isActive: boolean;
  periods?: FiscalPeriod[];
}

export interface FiscalPeriod {
  id: number;
  fiscalYearId: number;
  periodNumber: number;
  periodName: string;
  startDate: string;
  endDate: string;
  isClosed: boolean;
  closedBy?: number;
  closedAt?: string;
  isActive: boolean;
}

export interface RevenueCenter {
  id: number;
  revenueCenterCode: string;
  revenueCenterName: string;
  parentId: number | null;
  organizationId?: number;
  description?: string;
  isActive: boolean;
  children?: RevenueCenter[];
}

export interface Partner {
  id: number;
  partnerCode: string;
  partnerName: string;
  partnerType: 'CUSTOMER' | 'VENDOR' | 'BOTH';
  userProfileId?: number;
  organizationId?: number;
  taxId?: string;
  creditLimit: number;
  paymentTermsDays: number;
  defaultAccountId?: number;
  defaultAccount?: ChartOfAccount;
  isActive: boolean;
  createdAt: string;
}

export interface JournalEntry {
  id: number;
  entryNumber: string;
  entryType: 'ACTUAL' | 'BUDGET';
  entryDate: string;
  fiscalPeriodId: number;
  fiscalPeriod?: FiscalPeriod;
  referenceNumber?: string;
  description: string;
  totalDebit: number;
  totalCredit: number;
  status: 'DRAFT' | 'PENDING' | 'POSTED' | 'REVERSED';
  isAutoGenerated: boolean;
  sourceType?: string;
  sourceId?: number;
  postedBy?: number;
  postedAt?: string;
  lines: JournalEntryLine[];
  createdAt: string;
}

export interface JournalEntryLine {
  id?: number;
  journalEntryId?: number;
  lineNumber: number;
  accountId: number;
  account?: ChartOfAccount;
  revenueCenterId?: number;
  revenueCenter?: RevenueCenter;
  partnerId?: number;
  partner?: Partner;
  creditOrDebitId: number;
  amount: number;
  description?: string;
}

export interface Voucher {
  id: number;
  voucherNumber: string;
  voucherTypeId: number;
  voucherStatusId: number;
  voucherDate: string;
  fiscalPeriodId: number;
  fiscalPeriod?: FiscalPeriod;
  partnerId?: number;
  partner?: Partner;
  referenceNumber?: string;
  description?: string;
  totalAmount: number;
  currencyCode: string;
  exchangeRate: number;
  journalEntryId?: number;
  paymentMethod?: 'CASH' | 'CHEQUE' | 'TRANSFER' | 'OTHER';
  chequeNumber?: string;
  bankAccountId?: number;
  dueDate?: string;
  items: VoucherItem[];
  approvals: VoucherApproval[];
  createdAt: string;
}

export interface VoucherItemMaster {
  id: number;
  itemCode: string;
  itemName: string;
  accountId: number;
  account?: ChartOfAccount;
  description?: string;
  isActive: boolean;
}

export interface VoucherItem {
  id?: number;
  voucherId?: number;
  voucherItemId?: number;
  voucherItemMaster?: VoucherItemMaster;
  lineNumber: number;
  accountId: number;
  account?: ChartOfAccount;
  revenueCenterId?: number;
  creditOrDebitId: number;
  amount: number;
  taxAmount: number;
  description?: string;
}

export interface VoucherApproval {
  id: number;
  voucherId: number;
  approvalLevel: number;
  approverId: number;
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'SKIPPED';
  comments?: string;
  actionAt?: string;
}

export interface BankReconciliation {
  id: number;
  reconciliationNumber: string;
  bankAccountId: number;
  fiscalPeriodId: number;
  statementDate: string;
  statementBalance: number;
  bookBalance: number;
  adjustedBalance?: number;
  status: 'DRAFT' | 'IN_PROGRESS' | 'COMPLETED' | 'APPROVED';
  completedBy?: number;
  completedAt?: string;
  approvedBy?: number;
  approvedAt?: string;
  notes?: string;
  items: BankReconciliationItem[];
  createdAt: string;
}

export interface BankReconciliationItem {
  id?: number;
  reconciliationId?: number;
  itemType: 'OUTSTANDING_CHEQUE' | 'DEPOSIT_IN_TRANSIT' | 'BANK_CHARGE' | 'BANK_INTEREST' | 'ERROR' | 'OTHER';
  referenceNumber?: string;
  transactionDate: string;
  amount: number;
  description?: string;
  isCleared: boolean;
  clearedDate?: string;
  voucherId?: number;
}

export interface VoucherType {
  id: number;
  typeName: string;
  typeCode: string;
}

export interface VoucherStatus {
  id: number;
  statusName: string;
  statusCode: string;
}

// Form state types
export interface FormState<T> {
  data: T;
  errors: Record<string, string>;
  isSubmitting: boolean;
  isDirty: boolean;
}

// Table column definition
export interface TableColumn<T> {
  key: keyof T | string;
  header: string;
  width?: string;
  align?: 'left' | 'center' | 'right';
  render?: (value: unknown, row: T) => React.ReactNode;
  sortable?: boolean;
}

// Pagination
export interface PaginationState {
  page: number;
  pageSize: number;
  total: number;
}

// Filter
export interface FilterState {
  search: string;
  status?: string;
  dateFrom?: string;
  dateTo?: string;
  [key: string]: string | undefined;
}
