FROM quay.io/wildfly/wildfly:31.0.0.Final-jdk17

# Add MariaDB driver module
ADD mariadb-module.xml /opt/jboss/wildfly/modules/system/layers/base/org/mariadb/main/module.xml
ADD https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/3.1.4/mariadb-java-client-3.1.4.jar /opt/jboss/wildfly/modules/system/layers/base/org/mariadb/main/

# Copy standalone configuration with datasource
COPY standalone.xml /opt/jboss/wildfly/standalone/configuration/

# Expose HTTP and Admin ports
EXPOSE 8080 9990

# Start WildFly in standalone mode
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
