FROM quay.io/wildfly/wildfly:27.0.1.Final-jdk17

USER root

# Create MySQL module directory
RUN mkdir -p /opt/jboss/wildfly/modules/system/layers/base/com/mysql/main

# Download MySQL connector
ADD https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.1.0/mysql-connector-j-8.1.0.jar /opt/jboss/wildfly/modules/system/layers/base/com/mysql/main/

# Create module.xml for MySQL
RUN echo '<?xml version="1.0" encoding="UTF-8"?>\n\
<module xmlns="urn:jboss:module:1.9" name="com.mysql">\n\
    <resources>\n\
        <resource-root path="mysql-connector-j-8.1.0.jar"/>\n\
    </resources>\n\
    <dependencies>\n\
        <module name="javax.api"/>\n\
        <module name="javax.transaction.api"/>\n\
    </dependencies>\n\
</module>' > /opt/jboss/wildfly/modules/system/layers/base/com/mysql/main/module.xml

# Add management user
RUN /opt/jboss/wildfly/bin/add-user.sh admin admin123 --silent

# Configure datasource using CLI script file
COPY setup-datasource.cli /opt/jboss/wildfly/
RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/wildfly/setup-datasource.cli

# Fix permissions
RUN chown -R jboss:jboss /opt/jboss/wildfly

USER jboss

EXPOSE 8080 9990

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
